### ISSUE TITLE
Valid edi-x12 file but formatting fails with no ISA found

### ISSUE THREAD

**Issue by jmfrank63** [Silvenga/vscode-edi-x12-support#13]
I attached the file (renamed to .txt) as it is. Manually replacing ~ with ~\n works.

[RA0219798_T_NUFACTOR_856_BP899883663_20190917065901.X12.txt](https://github.com/Silvenga/vscode-edi-x12-support/files/3635439/RA0219798_T_NUFACTOR_856_BP899883663_20190917065901.X12.txt)

The extension is really cool, but kind of cumbersome without formatting ;-)

**Comment by Silvenga** [comment]
ISA11 defines the repeating element separator. Since that's a 'U' here, the parsing engine thinks that ISA08 is only 11 characters (which is invalid) during a self-check.

It looks like X12 00402 is the first version where a repeating separator exists. Can you confirm (I have no knowledge of 00401)?

**Comment by Silvenga** [comment]
In any case, should be handled in 1.1.0.

**Comment by jmfrank63** [comment]
Hi Mark,

thanks for looking into this. I am rather new to X12 and EDI and your
plugin is very helpful for me. I will try to contact our long time
specialist on the version but cannot promise anything.

Thank you for providing this awesome plugin nevertheless.

Cheers

Johannes

**Comment by Silvenga** [comment]
Thanks @jmfrank63 - and let me know if the 1.1.0 fixes your issue. Feel free to re-open this issue if it doesn't.
